### ISSUE TITLE
bbx15-spi-test.dtsi link not working

### ISSUE THREAD

**Issue by Launchpad-McQ** [mvduin/py-uio#3]

**Comment by mvduin** [comment]
The link works fine for me, and I'm guessing you've already found the Makefile in that directory builds the overlays.

**Comment by Launchpad-McQ** [comment]
Yes I was misstaken regarding the link, and I tried to remove the issue but I couldn't find any way. Yes I found that the makefile builds the overlays. 

(I have been trying to reach you in the beagleboard x15 mailinglist, but it wont let me post anything there. I apologies if this is an inappropriate way to reach you and I'm thinking that maybe I can contribute to the documentation of py-uio, but I'm trying to get your pi-uio working on my x15 and right now got stuck trying to use your fork of u-boot. I built with the config am57xx-evm and installed it with 
sudo dd if=./u-boot/MLO of=${DISK} count=2 seek=1 bs=128k
sudo dd if=./u-boot/u-boot.img of=${DISK} count=4 seek=1 bs=384k
Now the problem is that it wont boot from the sd card. Could you perhaps point me in the right direction of what might be wrong? I'm suspecting that the u-boot is not configured straight away, but I'm not sure how it should be configured. A little help would save me a lot of time)

**Comment by mvduin** [comment]
Have you subscribed to the [mailing list](https://groups.google.com/forum/#!forum/beagleboard-x15)?

I'm have no idea why u-boot might not be working for you. I'm using the same config. Just in case, here are the build products I get, along with an install script. These definitely work for me:
[u-boot-2017.01-00468-g506adcc7f880.tar.gz](https://github.com/mvduin/py-uio/files/2425508/u-boot-2017.01-00468-g506adcc7f880.tar.gz)

**Comment by Launchpad-McQ** [comment]
Yes, but It just says "Your membership is pending" and has been for like two weeks, if not more. The install with that build and script work like a charm! (I'm assuming, or can I check somewhere if u-boot is doing any pinmux?)

I'm trying to build the overlays in the dts folder and get a syntax error:
`Error: bbx15-spi-test.dtsi:24.4-5 syntax error
FATAL ERROR: Unable to parse input tree
Makefile:15: recipe for target 'bbx15-spi-test.dtbo' failed
make: *** [bbx15-spi-test.dtbo] Error 1`

(full output: https://pastebin.com/ByBPiJrb )

edit:
I managed to compile it now by including dra.h in bbx15-spi-test.dtsi
`#include </opt/source/dtb-4.14-ti/include/dt-bindings/pinctrl/dra.h>`

I have the problem that spidev3.1 is not showing up in /dev/. I suppose it should be loaded with
`machinekit@BeagleBoard-X15:~/py-uio/dts$ sudo bin/add-overlay bbx15-spi-test.dtbo 
/sys/kernel/config/device-tree/overlays/bbx15-spi-test/status: unapplied
rmdir: removing directory, '/sys/kernel/config/device-tree/overlays/bbx15-spi-test'`
which does not work.

**Comment by mvduin** [comment]
Did it send a verification email that you missed maybe?

You can check pinmux with the [bbx15 version of my show-pins utility](https://github.com/mvduin/bbb-pin-utils/tree/bbx15-experimental).

Also, it seems I briefly forgot that the bbx15 doesn't use u-boot overlays at all and this example is meant to be included into your main dts. I've pushed a commit that adds a comment to clarify that, and to ensure the Makefile doesn't attempt to build an overlay from bbx15-related dtsi files.

I don't know whether it might theoretically be possible to use a runtime overlay for this, but I've never tried it on the x15 and runtime overlays are entirely deprecated anyway.

**Comment by mvduin** [comment]
To clarify the cause of that parse error from dtc: the pinmux declarations use constants and macros that are defined in [dt-bindings/pinctrl/dra.h](https://github.com/RobertCNelson/dtb-rebuilder/blob/4.14-ti/include/dt-bindings/pinctrl/dra.h) that is included by [dra7.dtsi](https://github.com/RobertCNelson/dtb-rebuilder/blob/4.14-ti/src/arm/dra7.dtsi#L11).
